### PR TITLE
Mavenize and... stuff

### PR DESCRIPTION
**Pull request by mbax**
I started with just mavenizing, fixing packages, and introducing minimizeJar. Then I used and included the Apache Commons Codec Base64 class instead of the jvm-specific one. Then I removed the jackson binaries because they're not needed. Then I fixed the indentation and other formatting to be consistent. Then I cleared up the code a bit, fixed a HORRIBLE PROBLEM in onDisable (for rare situations) and fixed what I believe was a problem in response handling. Feel free to grab as much or as little as you need.

### CODE REVIEW

**Comment by mbax** [comment]
Quite nice of you to strip all credit when committing. Classy, really. ._.

**Comment by nxtguy** [comment]
I couldn't auto merge so I needed to add things in manually.

**Comment by mbax** [comment]
In no reality does that mean you had to drop commit authorship and couldn't merge or cherrypick :P

**Comment by nxtguy** [comment]
Apologies, I didn't know I could change authorship of commit. I'm also new to using git for my projects so I didn't want to further complicate things by merging with original commits and cherrypick.

**Comment by nxtguy** [comment]
@mbax I've added credit in the commit comments. :)

**Pull request closed without merging**
